nutzam/nutzboot

nutzboot-starter/src/main/java/org/nutz/boot/NbApp.java
nutzboot-starter/src/main/java/org/nutz/boot/resource/StaredLogoLoaderDD.java
pom.xml

原来clone的是前几天的,改完了发现跟大叔最新的不一样,然后又重新clone了一份...添加启动logo

add start Nutz logo!!

---

nutzboot-starter-wkcache/pom.xml
nutzboot-starter-wkcache/src/main/java/org/nutz/boot/starter/nutz/wkcache/WkCacheStarter.java
nutzboot-starter-wkcache/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
pom.xml

add: 应大鲨鱼的威逼利诱,添加wkcache

---

nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-common/pom.xml
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-common/src/main/java/io/nutz/demo/zbus/rpc/MainLauncher.java
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-common/src/main/java/io/nutz/demo/zbus/rpc/service/TimeService.java
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-client/pom.xml
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-client/src/main/java/io/nutz/demo/zbus/rpc/ZbusRpcTimeClientLauncher.java
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-client/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-client/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-client/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-service/pom.xml
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-service/src/main/java/io/nutz/demo/zbus/rpc/ZbusRpcTimeServiceLauncher.java
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-service/src/main/java/io/nutz/demo/zbus/rpc/service/impl/TimeServiceImpl.java
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-service/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-zbus/nutzboot-demo-zbus-rpc-service/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-zbus/pom.xml
nutzboot-starter-zbus/pom.xml
nutzboot-starter-zbus/src/main/java/org/nutz/boot/starter/zbus/ZbusStarter.java
nutzboot-starter-zbus/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter

完成了RPC的部分, 没有做MQ, 原因是zbus的api大改,导致nutz-integration-zbus需要大改,所以晚点再弄mq吧

add: zbus starter

---

nutzboot-starter-jdbc/src/main/java/org/nutz/boot/starter/jdbc/DataSourceStarter.java
nutzboot-starter-jdbc/src/main/java/org/nutz/boot/starter/jdbc/DruidWebStatFilterStarter.java
nutzboot-starter-jdbc/src/main/java/org/nutz/boot/starter/jdbc/DruidWebStatServletStarter.java
nutzboot-starter-jdbc/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/WhaleFilterStarter.java
nutzboot-starter-nutz-mvc/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter-shiro/src/main/java/org/nutz/boot/starter/shiro/ShiroFilterStarter.java
nutzboot-starter-zbus/src/main/java/org/nutz/boot/starter/zbus/ZbusStarter.java

add: 简单版starter-shiro
add: druid的monitor映射
add: jetty的filter顺序,及容忍servlet和filter为null的情况

add: shiro starter及相关调整

---

nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-common/pom.xml
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-common/src/main/java/io/nutz/demo/dubbo/rpc/MainLauncher.java
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-common/src/main/java/io/nutz/demo/dubbo/rpc/service/TimeService.java
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/pom.xml
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/src/main/java/io/nutz/demo/dubbo/rpc/DubboRpcTimeClientLauncher.java
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/src/main/resources/dubbo.xml
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-client/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-service/pom.xml
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-service/src/main/java/io/nutz/demo/dubbo/rpc/DubboRpcTimeServiceLauncher.java
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-service/src/main/java/io/nutz/demo/dubbo/rpc/service/impl/TimeServiceImpl.java
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-service/src/main/resources/dubbo.xml
nutzboot-demo/nutzboot-demo-dubbo/nutzboot-demo-dubbo-rpc-service/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-dubbo/pom.xml
nutzboot-starter-dubbo/pom.xml
nutzboot-starter-dubbo/src/main/java/org/nutz/boot/starter/dubbo/DubboStarter.java
nutzboot-starter-dubbo/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter/src/main/java/org/nutz/boot/NbApp.java

add: dubbo starter支持读取dubbo.xml
add: NB打印启动时间

add: dubbo starter的简单版就绪

---

.travis.yml
nutzboot-demo/nutzboot-demo-dubbo/pom.xml
nutzboot-demo/nutzboot-demo-simple-dao/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/pom.xml
nutzboot-starter/src/main/java/org/nutz/boot/NbApp.java
nutzboot-starter/src/main/java/org/nutz/boot/tools/PropDocBean.java
nutzboot-starter/src/main/java/org/nutz/boot/tools/PropDocReader.java

* 将starter的@PropDoc读取为Map
* 修正NbApp,使其可以打印markdown表格形式的配置手册

add: @PropDoc的读取器

---

README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetx/dependency-reduced-pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/dependency-reduced-pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-ngrok/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/src/main/resources/shiro.ini
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java
nutzboot-starter-ngrok/pom.xml
nutzboot-starter-ngrok/src/main/java/org/nutz/boot/starter/ngrok/NgrokClientStarter.java
nutzboot-starter-ngrok/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter-shiro/src/main/java/org/nutz/boot/starter/shiro/ShiroEnv.java
nutzboot-starter-shiro/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter

add: 添加starter及对应的demo
change: README新增ngrok的描述

add:  starter-ngrok 内网穿透ngrok客户端

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-starter/pom.xml
nutzboot-starter/src/main/java/org/nutz/boot/NbApp.java
nutzboot-starter/src/main/java/org/nutz/boot/config/ConfigureLoader.java
nutzboot-starter/src/main/java/org/nutz/boot/config/impl/AbstractConfigureLoader.java
nutzboot-starter/src/main/java/org/nutz/boot/config/impl/PropertiesConfigureLoader.java
nutzboot-starter/src/test/java/org/nutz/boot/config/impl/PropertiesConfigureLoaderTest.java
nutzboot-starter/src/test/resources/log4j.properties

fix: https://gitee.com/nutz/nutzboot/issues/IG1C9

add: 支持命令行参数和profile设置

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-dao/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mvc-shiro/pom.xml

fix: 修正一下demo pom 的版本号

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml

其实就是 nutzboot-demo-simple-mvc，仅是将jetty换成了undertow

 add: nutzboot-demo-simple-undertow

---

README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/java/io/nutz/demo/simple/bean/User.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/java/io/nutz/demo/simple/module/UserModule.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-mongodb/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-mongodb/pom.xml
nutzboot-starter-mongodb/src/main/java/org/nutz/boot/starter/mongodb/NutMongoDbStarter.java
nutzboot-starter-mongodb/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter

初步实现了 mongodb 的 starter，并跑通了测试用例

 add: nutzboot-starter-mongodb 的实现及 demo

---

README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/java/io/nutz/demo/simple/bean/User.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/resources/sqls/user.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-beetlsql/src/main/resources/template/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-beetlsql/pom.xml
nutzboot-starter-beetlsql/src/main/java/org/nutz/boot/starter/beetlsql/BeetlSqlStarter.java
nutzboot-starter-beetlsql/src/main/java/org/nutz/boot/starter/beetlsql/NutzConnectionSource.java
nutzboot-starter-beetlsql/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
pom.xml

add: starter-beetlsql 及其demo

---

README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/dependency-reduced-pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-thymeleaf/src/main/resources/template/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-thymeleaf/pom.xml
nutzboot-starter-thymeleaf/src/main/java/org/nutz/boot/starter/thymeleaf/ThymeleafView.java
nutzboot-starter-thymeleaf/src/main/java/org/nutz/boot/starter/thymeleaf/ThymeleafViewMakerStarter.java
nutzboot-starter-thymeleaf/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
pom.xml

添加 thymeleaf 的支持

---

ChangeLog.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/java/io/nutz/demo/simple/bean/UserOrder.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/java/io/nutz/demo/simple/module/UserModule.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/resources/shardingjdbc.yaml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/resources/static/index.html
nutzboot-starter-sharding-jdbc/pom.xml
nutzboot-starter-sharding-jdbc/src/main/java/org/nutz/boot/starter/shardingjdbc/ShardingJdbcDataSourceStarter.java
nutzboot-starter-sharding-jdbc/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
pom.xml

add: starter-sharding-jdbc

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-urule/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-urule/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-urule/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-urule/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-urule/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-urule/pom.xml
nutzboot-starter-urule/src/main/java/org/nutz/boot/starter/urule/UruleServletStarter.java
nutzboot-starter-urule/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter-urule/src/main/resources/urule-spring-context.xml
nutzboot-starter/src/main/resources/META-INF/spring/nutzboot-spring-context.xml
pom.xml

change: nutzboot-spring-context.xml里面的bean应该全部懒加载

add: 添加starter-urule

---

nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java
nutzboot-starter-tomcat/pom.xml
nutzboot-starter-tomcat/src/main/java/org/nutz/boot/starter/tomcat/TomcatStarter.java
nutzboot-starter-undertow/src/main/java/org/nutz/boot/starter/undertow/UndertowStarter.java

1）修复tomcat不加载static下的模板文件问题.
2) tomcat启动和停止加入守护线程
3）三个容易代码简单优化

tomcat support and clean code

---

nutzboot-starter-mongodb/src/main/java/org/nutz/boot/starter/mongodb/NutMongoDbStarter.java

update: 增强NutMongoDbStarter

---

ChangeLog.md
README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/src/main/resources/template/index.vm
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-mongodb/src/main/java/org/nutz/boot/starter/mongodb/NutMongoDbStarter.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/NbMvcLoading.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/api/ActionLoaderFace.java
nutzboot-starter-undertow/pom.xml
nutzboot-starter-velocity/pom.xml
nutzboot-starter-velocity/src/main/java/org/nutz/boot/starter/velocity/VelocityView.java
nutzboot-starter-velocity/src/main/java/org/nutz/boot/starter/velocity/VelocityViewMakerStarter.java
nutzboot-starter-velocity/src/main/java/org/nutz/boot/starter/velocity/VelocityWebContext.java
nutzboot-starter-velocity/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
pom.xml

NB集成velocity
NB官网的velocity拼写错误了

NB集成velocity

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java

issue_55 增强jetty配置

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-jetty/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-tomcat/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-velocity/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-starter-jdbc/src/main/java/org/nutz/boot/starter/jdbc/DruidWebStatFilterStarter.java
nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/NutFilterStarter.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/WhaleFilterStarter.java
nutzboot-starter-shiro/src/main/java/org/nutz/boot/starter/shiro/ShiroFilterStarter.java
nutzboot-starter-tomcat/src/main/java/org/nutz/boot/starter/tomcat/TomcatStarter.java
nutzboot-starter-undertow/src/main/java/org/nutz/boot/starter/undertow/UndertowStarter.java
nutzboot-starter/src/main/java/org/nutz/boot/AppContext.java
nutzboot-starter/src/main/java/org/nutz/boot/starter/WebFilterFace.java

1. AppContext添加getBeans方法,按接口取出对象
2. 重构3个web容器获取Filter/Server/EventListener的逻辑
3. 移除配置项 web.filters.order
4. 增加配置项 web.filter.$name.order 配置项

change: 移除web.filters.order,改成按接口获取Filter并按order排序

---

nutzboot-starter-shiro/src/main/java/org/nutz/boot/starter/shiro/ShiroEnvStarter.java

加的可能不太全或者描述不太正确或者加的姿势不太对,欢迎指正哦 ٩(๑>◡<๑)۶

给shiro增加几个启动时的日志打印

---

nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-dao/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-dao/src/main/java/io/nutz/demo/simple/module/UserModule.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-dao/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-sharding-jdbc/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-undertow/src/main/resources/static/index.html
nutzboot-starter-jdbc/src/main/java/org/nutz/boot/starter/jdbc/DruidWebStatServletStarter.java
nutzboot-starter-jetty/src/main/java/org/nutz/boot/starter/jetty/JettyStarter.java
nutzboot-starter-nutz-mvc/src/main/java/org/nutz/boot/starter/nutz/mvc/NutFilterStarter.java
nutzboot-starter-swagger/src/main/java/org/nutz/boot/starter/swagger/SwaggerServletStarter.java
nutzboot-starter-undertow/src/main/java/org/nutz/boot/starter/undertow/ComboResourceManager.java
nutzboot-starter-undertow/src/main/java/org/nutz/boot/starter/undertow/UndertowStarter.java

过程是这样的:
改simple-dao, 加上swagger注解和链接,发现没提示druid用户名
改simple-sharding-jdbc, 加上swagger注解和链接,发现NutFilterStarter有点挫,改造一下
改simple-undertow, 加上swagger注解和链接, 发现404和乱码

fix: swagger可能乱码,undertow无法与swagger一起工作,druid stat view没打印用户名

---

ChangeLog.md
README.md
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-eureka-client/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-rabbitmq/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-rabbitmq/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-rabbitmq/src/main/java/io/nutz/demo/simple/service/RabbitTestService.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-rabbitmq/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-rabbitmq/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-xxl-job-executor/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-xxl-job-executor/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-xxl-job-executor/src/main/java/io/nutz/demo/simple/service/jobhandler/DemoJobHandler.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-xxl-job-executor/src/main/java/io/nutz/demo/simple/service/jobhandler/ShardingJobHandler.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-xxl-job-executor/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/pom.xml
nutzboot-starter/nutzboot-starter-rabbitmq/pom.xml
nutzboot-starter/nutzboot-starter-rabbitmq/src/main/java/org/nutz/boot/starter/rabbitmq/RabbitmqStarter.java
nutzboot-starter/nutzboot-starter-rabbitmq/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-starter/pom.xml
pom.xml

add: 添加starter-rabbitmq,其实就是把nutz-integration-rabbitmq包装一下,以后再扩展吧

---

ChangeLog.md
README.md
nutzboot-contrib/nutzboot-starter-activiti/pom.xml
nutzboot-contrib/nutzboot-starter-activiti/src/main/java/org/nutz/boot/starter/activiti/ActivitiSetupStarter.java
nutzboot-contrib/nutzboot-starter-activiti/src/main/java/org/nutz/boot/starter/activiti/ActivitiStarter.java
nutzboot-contrib/nutzboot-starter-activiti/src/main/resources/META-INF/nutz/org.nutz.boot.starter.NbStarter
nutzboot-contrib/pom.xml
nutzboot-demo/nutzboot-demo-cloud/README.md
nutzboot-demo/nutzboot-demo-cloud/nutzboot-demo-cloud-service/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-activiti/pom.xml
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-activiti/src/main/java/io/nutz/demo/simple/MainLauncher.java
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-activiti/src/main/resources/application.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-activiti/src/main/resources/log4j.properties
nutzboot-demo/nutzboot-demo-simple/nutzboot-demo-simple-activiti/src/main/resources/static/index.html
nutzboot-demo/nutzboot-demo-simple/pom.xml
pom.xml

add: 把nutzmore的activiti封装一下,完成starter-activiti
change: nutzboot-demo-cloud 应该用mysql数据库,h2的内存数据库在多service的情况下结果不对的

add: 把nutzmore的activiti封装一下,完成starter-activiti
